series: Vector Mathematics
title: Introduction to Vector Math
author:
  name: Andrew Litfin
  email:
  github: astrodude80
description: This example gives a brief tutorial on the basics of vectors.
language: C++
tags:
  - Math
extra_resources:
  - title: The Wikipedia article on Euclidean vectors
    link: https://en.wikipedia.org/wiki/Euclidean_vector
connections:
